# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SoundBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundBoard
  pod 'Google-Mobile-Ads-SDK'

  target 'SoundBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundBoardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
